languageCode = "de"
removePathAccents = true
disableFastRender = true
buildFuture = true
paginatePath = "seite"
paginate = 12
pygmentsCodefences = true

[params]
title = "lyschneider"
description = "lyschneider | Levyn Schneider Film & Foto"
favicon = "/img/favicon.png"
image = "/img/favicon.png"
copyright = "Â© 2022 by Levyn Schneider"

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe= true